---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.
fabric_name: DC1_FABRIC

underlay_routing_protocol: EBGP

overlay_routing_protocol: EBGP
# Enable vlan aware bundles
evpn_vlan_aware_bundles: true

# bgp peer groups passwords
#bgp_peer_groups:
#  IPv4_UNDERLAY_PEERS:
#   password: "AQQvKeimxJu+uGQ/yYvv9w=="
#  EVPN_OVERLAY_PEERS:
#      password: "q+VNViP5i4rVjW1cxFv2wA=="
#  MLAG_IPv4_UNDERLAY_PEER:
#      password: "vnEaG8gMeQf3d3cN6PktXQ=="
# Spine Switches
spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_defaults:
      #- update wait-for-convergence
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  leaf_as_range: 65101-65132
  nodes:
    DC1_SPINE1:
      id: 1
      mgmt_ip: 192.168.0.11/24
    DC1_SPINE2:
      id: 2
      mgmt_ip: 192.168.0.12/24
# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair
l3leaf:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65100
    uplink_switches: [DC1_SPINE1, DC1_SPINE2]
    uplink_interfaces: [Ethernet2, Ethernet3]
    mlag_interfaces: [Ethernet1, Ethernet6]
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_peer_ipv4_pool: 10.255.255.0/24
    mlag_peer_l3_ipv4_pool: 10.255.254.0/24
    bgp_defaults:
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  node_groups:
    DC1_LEAF_POD1:
      bgp_as: 65101
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone_pod1 ]
      nodes:
        DC1_LEAF1:
          id: 1
          mgmt_ip: 192.168.0.21/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
        DC1_LEAF2:
          id: 2
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
    DC1_LEAF_POD2:
      bgp_as: 65102
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone_pod2 ]
      nodes:
        DC1_LEAF3:
          id: 3
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
        DC1_LEAF4:
          id: 4
          mgmt_ip: 192.168.0.24/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in vEOS-LAB.
# Refer to design guide

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
